{
 "title": "PV Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "deye-inverter",
     "query": "from(bucket: \"solar\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"solar_power\" and r._field == \"leistung\")\n  |> last()",
     "select": [
      [
       { "params": [ "w" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "grid" }
     ]
    }
   ]
  },
  {
   "title": "Power over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Grid",
     "measurement": "deye-inverter",
     "query": "from(bucket: \"solar\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"solar_power\" and r._field == \"leistung\")\n  |> aggregateWindow(every: 1m, fn: mean)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "w" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "grid" }
     ]
    },
    {
     "alias": "PV 1",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "w" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv1" }
     ]
    },
    {
     "alias": "PV 2",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "w" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv2" }
     ]
    }
   ]
  },
  {
   "title": "Harvested Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "kWh_total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "grid" }
     ]
    },
    {
     "alias": "Today",
     "measurement": "deye-inverter",
     "query": "from(bucket: \"solar\")\n  |> range(start: today())\n  |> filter(fn: (r) => r._measurement == \"solar_power\" and r._field == \"leistung\")\n  |> map(fn: (r) => ({ r with wattstunden: r._value * 10.0 / 3600.0 }))\n  |> sum(column: \"wattstunden\")",
     "select": [
      [
       { "params": [ "kWh_today" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "grid" }
     ]
    }
   ]
  },
  {
   "title": "Absolute Peak Power",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Grid",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "w" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "grid" }
     ]
    },
    {
     "alias": "PV1",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "w" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv1" }
     ]
    },
    {
     "alias": "PV2",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "w" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv2" }
     ]
    }
   ]
  },
  {
   "title": "Today's Peak Power",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Grid",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "w" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "grid" }
     ]
    },
    {
     "alias": "PV1",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "w" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv1" }
     ]
    },
    {
     "alias": "PV2",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "w" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv2" }
     ]
    }
   ]
  },
  {
   "title": "PV Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "V - PV1",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "v" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv1" }
     ]
    },
    {
     "alias": "V - PV2",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "v" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv2" }
     ]
    },
    {
     "alias": "I - PV1",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "i" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv1" }
     ]
    },
    {
     "alias": "I - PV2",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "i" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "pv2" }
     ]
    }
   ]
  },
  {
   "title": "Inverter Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Radiator Temperature",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "radiator_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "inverter" }
     ]
    },
    {
     "alias": "Efficiency",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "efficiency" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "inverter" }
     ]
    }
   ]
  },
  {
   "title": "Grid Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Voltage",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "v" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "grid" }
     ]
    },
    {
     "alias": "Frequency",
     "measurement": "deye-inverter",
     "select": [
      [
       { "params": [ "hz" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Class::tag", "operator": "=", "value": "grid" }
     ]
    }
   ]
  }
 ]
}